/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import databaseapp.SendEmail;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Ernest Bieś, PWSZ Tarnów 2019
 */
public class EmailGUI extends javax.swing.JFrame {

    private List<String> addressList;
    private String recipientsTO, recipientsDW, recipientsUDW;
    private DefaultListModel jModel;
    
    public EmailGUI(List<String> adList) {
        initComponents();
        addressList = new ArrayList<>();
        addressList = adList;
        recipientsTO = "";
        recipientsDW = "";
        recipientsUDW = "";        
        jModel = new DefaultListModel();
        jModel.addAll(addressList);
        jList1.setModel(jModel);
        jButtonSend.setEnabled(false);
        jTextFieldTO.setEditable(false);
        jTextFieldDW.setEditable(false);
        jTextFieldUDW.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldSubject = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();
        jLabelDW = new javax.swing.JLabel();
        jLabelUDW = new javax.swing.JLabel();
        jTextFieldDW = new javax.swing.JTextField();
        jTextFieldUDW = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButtonTO = new javax.swing.JButton();
        jButtonDW = new javax.swing.JButton();
        jButtonUDW = new javax.swing.JButton();
        jButtonRemoveAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Database Connection Application 1.0 - E-mail sender @ Ernest Bieś");

        jLabel2.setText("List of all recipients:");

        jLabel3.setText("TO:");

        jTextFieldTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTOActionPerformed(evt);
            }
        });

        jLabel4.setText("Subject:");

        jLabel5.setText("Message:");

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setRows(5);
        jScrollPane1.setViewportView(jTextAreaMessage);

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jLabelDW.setText("DW:");

        jLabelUDW.setText("UDW:");

        jTextFieldDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDWActionPerformed(evt);
            }
        });

        jTextFieldUDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUDWActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList1);

        jButtonTO.setText("Add recipients TO");
        jButtonTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTOActionPerformed(evt);
            }
        });

        jButtonDW.setText("Add recipients DW");
        jButtonDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDWActionPerformed(evt);
            }
        });

        jButtonUDW.setText("Add recipients UDW");
        jButtonUDW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUDWActionPerformed(evt);
            }
        });

        jButtonRemoveAll.setText("Remove all recipients");
        jButtonRemoveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jButtonSend)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUDW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUDW, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDW)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDW, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTO, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonDW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonUDW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRemoveAll))))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDW)
                            .addComponent(jTextFieldDW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUDW)
                            .addComponent(jTextFieldUDW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButtonSend)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUDW)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveAll)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTOActionPerformed

    private void jTextFieldDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDWActionPerformed

    private void jTextFieldUDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUDWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUDWActionPerformed

    private void jButtonRemoveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveAllActionPerformed
        clearRecipients();
    }//GEN-LAST:event_jButtonRemoveAllActionPerformed

    private void jButtonTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTOActionPerformed
        selectRecipients("TO");
        checkListChanges();
    }//GEN-LAST:event_jButtonTOActionPerformed

    private void jButtonDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDWActionPerformed
        selectRecipients("DW");
        checkListChanges();
    }//GEN-LAST:event_jButtonDWActionPerformed

    private void jButtonUDWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUDWActionPerformed
        selectRecipients("UDW");
        checkListChanges();
    }//GEN-LAST:event_jButtonUDWActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        SendEmail se = new SendEmail(jTextFieldTO.getText(), jTextFieldSubject.getText(), jTextAreaMessage.getText());
        se.addRecipients(jTextFieldDW.getText(), "DW");
        se.addRecipients(jTextFieldUDW.getText(), "UDW");

        if(se.send()){
            JOptionPane.showMessageDialog(new JFrame("Email information"), "E-mail has been sucessfully sent.");
            clearRecipients();
            jTextFieldSubject.setText("");
            jTextAreaMessage.setText("");
        }else{
            JOptionPane.showMessageDialog(new JFrame("Email information"), "Error while sending an email", "Warning", JOptionPane.WARNING_MESSAGE);  
        }
    
    }//GEN-LAST:event_jButtonSendActionPerformed

    //Metoda sprawdzająca zmiany w liście odbiorców
    private void checkListChanges(){
        if(!jTextFieldTO.getText().isEmpty() || !jTextFieldDW.getText().isEmpty() || !jTextFieldUDW.getText().isEmpty()){
            jButtonSend.setEnabled(true);
        }else{
            jButtonSend.setEnabled(false);
        }
    }
    
    //Metoda czyszcząca listę wszystkich zaznaczonych wcześniej odbiorców
    private void clearRecipients(){
        jTextFieldTO.setText("");
        jTextFieldDW.setText("");
        jTextFieldUDW.setText("");
            
        recipientsTO = "";
        recipientsDW = "";
        recipientsUDW = "";

        jModel.clear();
        jModel.addAll(addressList);
        jList1.setModel(jModel);
        jButtonSend.setEnabled(false);
    }
    
    //Metoda służąca do wyboru odbiorcy e-maila - TO, DW, UDW
    private void selectRecipients(String type){
        String s = "";
        for(int i=0; i < jList1.getSelectedValuesList().size() ;i++){
            if(i < jList1.getSelectedValuesList().size()-1){
                s = s + jList1.getSelectedValuesList().get(i) + ",";
            }else{
                s = s + jList1.getSelectedValuesList().get(i);
            }
        }
        if (!"".equals(s)) {
            if ("TO".equals(type)) {
                if (recipientsTO.isEmpty()) {
                    recipientsTO = s;
                } else {
                    recipientsTO = recipientsTO + ',' + s;
                }

                jTextFieldTO.setText(recipientsTO);
            }

            if ("DW".equals(type)) {
                if(recipientsDW.isEmpty()){
                    recipientsDW = s;
                } else {
                    recipientsDW = recipientsDW + ',' + s;
                }
               
                jTextFieldDW.setText(recipientsDW);
            }

            if ("UDW".equals(type)) {
                if(recipientsUDW.isEmpty()){
                    recipientsUDW = s;
                } else {
                    recipientsUDW = recipientsUDW + ',' + s;
                }
                
                jTextFieldUDW.setText(recipientsUDW);
            }
        
            List<String> lista = new ArrayList<>();
            
            for(int i=0;i<jModel.size();i++){
                lista.add(jModel.get(i).toString());
            }
            
            for(int i=0; i<jList1.getSelectedValuesList().size(); i++){
                lista.remove(jList1.getSelectedValuesList().get(i));
            }
            jModel.clear();
            jModel.addAll(lista);
            jList1.setModel(jModel);
        }     
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDW;
    private javax.swing.JButton jButtonRemoveAll;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonTO;
    private javax.swing.JButton jButtonUDW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDW;
    private javax.swing.JLabel jLabelUDW;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JTextField jTextFieldDW;
    private javax.swing.JTextField jTextFieldSubject;
    private javax.swing.JTextField jTextFieldTO;
    private javax.swing.JTextField jTextFieldUDW;
    // End of variables declaration//GEN-END:variables
}